# Generated by Django 4.1.4 on 2022-12-31 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Split', '0003_entity_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
